apiVersion: v1
kind: Service
metadata:
  name: frontend # add service name "frontend"  coreDNS entry 
  labels:
    app: frontend # Tag 
spec:
  type: NodePort # LoadBalancer
  ports:
    - port: 80
  #  - nodePort: 30090
  selector:
    app: frontend # Taking you pods 
  
  https://github.com/nigelpoulton/TheK8sBook/tree/master/networking